// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB21TRJYPynCDBrv1W3wmRXll206T8C_wA',
    appId: '1:827483157969:web:9cf06e426783651a469cf0',
    messagingSenderId: '827483157969',
    projectId: 'mybbf-4113e',
    authDomain: 'mybbf-4113e.firebaseapp.com',
    storageBucket: 'mybbf-4113e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNbDvzGYw3clOl6eqJ65HsKns95hfdmYo',
    appId: '1:827483157969:android:3a966142169e218a469cf0',
    messagingSenderId: '827483157969',
    projectId: 'mybbf-4113e',
    storageBucket: 'mybbf-4113e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZU7EA70fC1gkzNa0q8qMqtAjczR8EWWc',
    appId: '1:827483157969:ios:e9ccba41c9f4853b469cf0',
    messagingSenderId: '827483157969',
    projectId: 'mybbf-4113e',
    storageBucket: 'mybbf-4113e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZU7EA70fC1gkzNa0q8qMqtAjczR8EWWc',
    appId: '1:827483157969:ios:e9ccba41c9f4853b469cf0',
    messagingSenderId: '827483157969',
    projectId: 'mybbf-4113e',
    storageBucket: 'mybbf-4113e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB21TRJYPynCDBrv1W3wmRXll206T8C_wA',
    appId: '1:827483157969:web:707ce7a30b187116469cf0',
    messagingSenderId: '827483157969',
    projectId: 'mybbf-4113e',
    authDomain: 'mybbf-4113e.firebaseapp.com',
    storageBucket: 'mybbf-4113e.firebasestorage.app',
  );
}
